### ISSUE TITLE
[Improvement] Model definitions

### ISSUE THREAD

**Issue by mktozk** [keras-team/keras-applications#18]
Some model definitions are not precise:
* [Original MobileNetV2 models](https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet) dose not have any densely-connected layers.
* [Resnet50](https://arxiv.org/abs/1512.03385) weights are initialized by using `he_normal`.

**Comment by taehoonlee** [comment]
Thank you for the comments @mktozk.

- For `MobileNetV2`, can you elaborate on the mismatch you think? The equivalence between `tensorflow/models` and `keras-applications` has already been checked.
- For `ResNet50`, the initializers are `he_normal`, `xavier` (the tf-layer default), and  `glorot` (the keras default) in `facebook/fb.resnet.torch`, `tensorflow/models`, and `keras-applications`, respectively. The original one is `he_normal` as you said, but they didn't show significant differences.

**Comment by mktozk** [comment]
Thank you for your reply.

* For computing outputs, a fully-connected layer is used in `keras-applications` while a 1x1 conv2d is used in `tensorflow/models`. Their operations are not same but provide same results in this case.
* You are right. There are little differences. FYI: `he_normal` initializers are used in [Resnet implementation by chainer](https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/resnet.py). In this implementation, an initialization depends on using pretrained weights.

My comments will be helpful to increase reproducibility and to reduce ambiguity.

**Comment by taehoonlee** [comment]
Note that all the models in here are for only inference.

- In the very last layer, the `Dense(classes)` and the `Conv2D(classes, 1)` produce the same results for 224x224 inputs. This is just a style difference rather than a mismatch. Actually, I also want to replace `Dense(classes)` with `Conv2D(classes, 1)` but the replacement requires updates of all the weight files for all the models including `MobileNetV2`. That is a very big construction.
- OK. I'll update with `kernel_initializer='he_normal'`.

**Comment by taehoonlee** [comment]
@mktozk, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
