### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by taehoonlee** [keras-team/keras-applications#9]
Since Keras 2.2.0, integration tests have been failed (see [test codes](https://github.com/keras-team/keras-applications/blob/master/tests/integration_tests.py#L22) and [CI results](https://travis-ci.org/keras-team/keras-applications/jobs/389538553)). The `tf.keras.engine` does not exist even in the latest `tensorflow==1.9.0rc0`. @fchollet, Don't we have no choice but to wait for `tensorflow==1.9.0`?

**Comment by fchollet** [comment]
Welp. `from tensorflow.python.keras import engine` works, so we can use that.

Otherwise it seems to me like we should either make make `engine` a public module in all versions of Keras, or make `keras_applications` not rely on it. We only rely on it because of `get_source_inputs` or something like that. We could package that module with `keras_applications`.

**Comment by taehoonlee** [comment]
@fchollet, Or how about this?
1. add `from ..engine.network import get_source_inputs` into `keras/utils/layer_utils.py`,
2. add `from .layer_utils import get_source_inputs` into `keras/utils/__init__.py`,
3. replace `engine.get_source_inputs` with `utils.get_source_inputs` for all the applications.

**Comment by fchollet** [comment]
Sounds good to me.
